# Hashicorp Vault Helm Chart
global:
  tlsDisable: false
  secretStore:
    name: vault-backend
    kind: ClusterSecretStore

clusterGroup:
  name: hub
  isHubCluster: true

  namespaces:
  - vault
  - golang-external-secrets
  - cert-manager
  - manufacturing-dev
  - open-cluster-management

  projects:
  - hub

  subscriptions:
    amqstreams-dev:
      name: amq-streams
      namespace: manufacturing-dev
      channel: amq-streams-1.8.x
      csv: amqstreams.v1.8.4

    cert-manager-dev:
      name: cert-manager
      channel: stable
      source: community-operators
      csv: cert-manager.v1.10.1

    acm:
      name: advanced-cluster-management
      namespace: open-cluster-management
      channel: release-2.6

  applications:
    acm:
      name: acm
      namespace: open-cluster-management
      project: hub
      path: common/acm
      ignoreDifferences:
      - group: internal.open-cluster-management.io
        kind: ManagedClusterInfo
        jsonPointers:
          - /spec/loggingCA

    vault:
      name: vault
      namespace: vault
      project: hub
      path: common/hashicorp-vault

    golang-external-secrets:
      name: golang-external-secrets
      namespace: golang-external-secrets
      project: hub
      path: common/golang-external-secrets

    ocp-install:
      name: ocp-install
      namespace: manufacturing-dev
      project: hub
      path: charts/hub/ocp-install

    ocp-srv-install:
      name: ocp-srv-install
      namespace: manufacturing-dev
      project: hub
      path: charts/hub/ocp-srv-install


  imperative:
    # NOTE: We *must* use lists and not hashes. As hashes lose ordering once parsed by helm
    # The default schedule is every 10 minutes: imperative.schedule
    # Total timeout of all jobs is 1h: imperative.activeDeadlineSeconds
    # imagePullPolicy is set to always: imperative.imagePullPolicy
    # For additional overrides that apply to the jobs, please refer to
    # https://hybrid-cloud-patterns.io/imperative-actions/#additional-job-customizations
    # The openshift service ca job needs to be able to create a secret in the vault namespace
    clusterRoleYaml:
      - apiGroups:
        - '*'
        resources:
        - '*'
        verbs:
        - get
        - list
        - watch
      - apiGroups:
        - '*'
        resources:
        - secrets
        verbs:
        - create
        - delete
        - get
        - list
        - patch
        - update

    schedule: "*/3 * * * *"
    jobs:
    - name: openshift-service-ca-secret
      playbook: ansible/playbooks/copy-service-ca-crt-to-secret.yml
    - name: configure-vault-pki-backends
      playbook: ansible/playbooks/on-hub-configure-vault-pki.yml
      timeout: 120

  managedClusterGroups:
    exampleRegion:
      name: group-one
      acmlabels:
      - name: clusterGroup
        value: group-one
      helmOverrides:
      - name: clusterGroup.isHubCluster
        value: false
